# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: libadwaita
  version: "1.9.0"
  version_majmin: ${{ (version | split('.'))[:2] | join('.') }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://download.gnome.org/sources/libadwaita/${{ version_majmin }}/libadwaita-${{ version }}.tar.xz
  sha256: 817837bf06363db5bbfce66085136eff1436af6625dfabff3ca08b87bfca1b6b
  patches:
    - 0001-remove-appstream-dependency.patch

build:
  number: 2
  script:
    - if: win
      then: |
        meson setup %MESON_ARGS% ^
          --prefix=%LIBRARY_PREFIX% ^
          --default-library=shared ^
          --wrap-mode=nofallback ^
          -Dintrospection=enabled ^
          -Dtests=false ^
          -Dexamples=false ^
          -Dvapi=false ^
          builddir
        ninja -v -C builddir -j %CPU_COUNT%
        ninja -C builddir install -j %CPU_COUNT%
      else: |
        if [[ "${CONDA_BUILD_CROSS_COMPILATION:-0}" == "1" ]]; then
          for tool in glib-mkenums glib-genmarshal; do
              cp -f ${BUILD_PREFIX}/bin/${tool} ${PREFIX}/bin/${tool}
          done          
          echo '#!/bin/bash' > ${PREFIX}/bin/glib-compile-resources
          echo "exec ${BUILD_PREFIX}/bin/glib-compile-resources \"\$@\"" >> ${PREFIX}/bin/glib-compile-resources
          chmod +x ${PREFIX}/bin/glib-compile-resources
          INTROSPECTION=disabled
        else
          INTROSPECTION=enabled
        fi
        meson setup ${MESON_ARGS} \
            --prefix=$PREFIX \
            --default-library=shared \
            --wrap-mode=nofallback \
            -Dintrospection=${INTROSPECTION} \
            -Dtests=false \
            -Dexamples=false \
            -Dvapi=false \
            builddir
        ninja -v -C builddir -j ${CPU_COUNT}
        ninja -C builddir install -j ${CPU_COUNT}

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - meson >=0.63.0
    - ninja
    - pkg-config
    - gobject-introspection
    - python
    - sassc
    - glib
  host:
    - freetype
    - gettext
    - glib
    - glib >=2.80.0
    - graphene
    - gtk4 >=4.19.4
    - fribidi
    - pango
    - gobject-introspection
    - zlib
    - expat
    - python
    - if: unix
      then:
        - appstream
        - libxml2-devel
        - libxmlb
  run:
    - python
  run_exports:
    - ${{ pin_subpackage('libadwaita', upper_bound='x.x') }}
  ignore_run_exports:
    by_name:
      - libexpat
      - adwaita-icon-theme
      - libzlib
      - libxmlb
      - libfreetype6
      - libxml2-16

tests:
  - package_contents:
      files:
        - if: unix
          then:
            - lib/pkgconfig/libadwaita-1.pc
        - if: win
          then:
            - Library/lib/pkgconfig/libadwaita-1.pc
      lib:
        - if: unix
          then:
            - libadwaita-1*
        - if: win
          then:
            - adwaita-1*

about:
  homepage: https://gnome.pages.gitlab.gnome.org/libadwaita/
  summary: 'Building blocks for modern GNOME applications'
  description: |
    Adwaita offers application developers many widgets and
    objects to build GNOME applications scaling from desktop
    workstations to mobile phones. 
  license: LGPL-2.1-or-later
  license_file: COPYING
  documentation: https://gnome.pages.gitlab.gnome.org/libadwaita/doc/
  repository: https://gitlab.gnome.org/GNOME/libadwaita

extra:
  recipe-maintainers:
    - danyeaw
    - pkgw
    - ryanvolz
    - haecker-felix
